### ISSUE TITLE
ACME: Roadmap

### ISSUE THREAD

**Issue by whitekid** [whitekid/scas#1]
- [x] jws signature, account, order, authorization, challenges
- [x] 8. Identifier Validation Challenges
  - [x] 8.3. HTTP challenge
    - [x] #2
  - [x] #5
- [x] improve error handling
- [x] #6
- [x] #7
- [x] #8
- [x] #10
- [x] #9
## Next
- [ ] `ExternalAccountRequired`
- [ ] `CAAIdentities`
- [ ] 7.3.4 external account binding
- [ ] 7.4.1 pre-authorization
- [ ] 7.5.2. Deactivating an authorization
- [ ] 9. IANA Considerations
